import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — PublishRoad",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: "var(--background)" }}>
      <div className="max-w-[720px] mx-auto px-4 sm:px-6 py-20">
        <h1
          className="text-4xl font-bold mb-2"
          style={{ fontFamily: "var(--font-heading)", color: "var(--dark)" }}
        >
          Privacy Policy
        </h1>
        <p className="text-slate-400 mb-12 font-light">Last updated: March 2026</p>

        <div className="space-y-8">
          {[
            {
              title: "1. Information We Collect",
              body: "We collect information you provide when creating an account (name, email, password), information generated by using our service (product URLs, keywords, curation results), and technical information (IP address for security, browser type).",
            },
            {
              title: "2. How We Use Your Information",
              body: "We use your information to: provide and improve our service, process payments, send transactional emails (verification, receipts, curation results), detect and prevent fraud, and comply with legal obligations.",
            },
            {
              title: "3. Data Storage & Security",
              body: "Your data is stored on secure servers hosted by Supabase (PostgreSQL) in the EU/US. Sensitive fields such as payment information are encrypted. Passwords are hashed using bcrypt. We implement industry-standard security measures.",
            },
            {
              title: "4. Payment Information",
              body: "We do not store your credit card details. All payment processing is handled by Stripe, which is PCI-DSS compliant. We store only a Stripe customer reference ID, encrypted at rest.",
            },
            {
              title: "5. Data Sharing",
              body: "We do not sell your personal data. We share data only with: Stripe (payment processing), Resend (email delivery), Sentry (error monitoring), and PostHog (analytics). All third parties are contractually obligated to protect your data.",
            },
            {
              title: "6. Your Rights (GDPR)",
              body: "You have the right to: access your data, correct inaccurate data, delete your account and data, export your data, and opt out of non-essential communications. To exercise these rights, contact privacy@publishroad.com.",
            },
            {
              title: "7. Cookies",
              body: "We use only essential cookies for session management and authentication. We use PostHog for analytics, which may set cookies. You can opt out of analytics tracking in your profile settings.",
            },
            {
              title: "8. Data Retention",
              body: "We retain your account data for as long as your account is active. Upon account deletion, your personal data is removed within 30 days. Anonymized usage data may be retained for analytics purposes.",
            },
            {
              title: "9. Contact",
              body: "For privacy questions or data requests, contact us at privacy@publishroad.com.",
            },
          ].map((section) => (
            <section
              key={section.title}
              className="bg-white rounded-2xl p-6"
              style={{ boxShadow: "0 2px 12px rgba(91,88,246,0.05)", border: "1px solid rgba(226,232,240,0.8)" }}
            >
              <h2
                className="text-lg font-semibold mb-3"
                style={{ fontFamily: "var(--font-heading)", color: "var(--dark)" }}
              >
                {section.title}
              </h2>
              <p className="text-slate-500 font-light leading-relaxed">{section.body}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
